# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/ibp.com_ibpcas.yaml
- bases/ibp.com_ibppeers.yaml
- bases/ibp.com_ibporderers.yaml
- bases/ibp.com_ibpconsoles.yaml
- bases/ibp.com_organizations.yaml
- bases/ibp.com_federations.yaml
- bases/ibp.com_proposals.yaml
- bases/ibp.com_votes.yaml
- bases/ibp.com_networks.yaml
- bases/ibp.com_channels.yaml
- bases/ibp.com_endorsepolicies.yaml
- bases/ibp.com_chaincodes.yaml

# +kubebuilder:scaffold:crdkustomizeresource

patchesStrategicMerge:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
#- patches/webhook_in_ibpcas.yaml
#- patches/webhook_in_ibppeers.yaml
#- patches/webhook_in_ibporderers.yaml
#- patches/webhook_in_ibpconsoles.yaml
#- patches/webhook_in_organizations.yaml
#- patches/webhook_in_federations.yaml
#- patches/webhook_in_networks.yaml
#- patches/webhook_in_channels.yaml
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [CERTMANAGER] To enable webhook, uncomment all the sections with [CERTMANAGER] prefix.
# patches here are for enabling the CA injection for each CRD
#- patches/cainjection_in_ibpcas.yaml
#- patches/cainjection_in_ibppeers.yaml
#- patches/cainjection_in_ibporderers.yaml
#- patches/cainjection_in_ibpconsoles.yaml
#- patches/cainjection_in_organizations.yaml
#- patches/cainjection_in_federations.yaml
#- patches/cainjection_in_networks.yaml
#- patches/cainjection_in_channels.yaml
# +kubebuilder:scaffold:crdkustomizecainjectionpatch

# the following config is for teaching kustomize how to do kustomization for CRDs.
configurations:
- kustomizeconfig.yaml
